### ISSUE TITLE
Internal Error Occurred When Comparing 2 PBIT files

### ISSUE THREAD

**Issue by samaguire** [microsoft/Analysis-Services#47]
I tried comparing the two attached files and immediately get an internal error occured error.
[2020-02-20 - PBI Remodel.zip](https://github.com/microsoft/Analysis-Services/files/4346899/2020-02-20.-.PBI.Remodel.zip)

**Comment by christianwade** [comment]
Thanks for raising. This is a bug in TOM serialization we just found out from another case today. It's been escalated but will take a few weeks to roll out.

In the meantime, the issue seems to be associated with query groups in PQ. As a temporary workaround if you are blocked would be to try removing them.

![Query groups](https://user-images.githubusercontent.com/20731873/77133262-b3b90900-6a1f-11ea-9f37-5f55cd61c20c.png)

**Comment by samaguire** [comment]
Thanks for the update. Will give the workaround a go.

Regards
Stephen

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rian-II** [comment]
I'd just like to confirm that I'm experiencing the same issue (and would appreciate an update when it has rolled out).

I have quite a few folders in PQ, so I don't think I'll be using the workaround right now.
![image](https://user-images.githubusercontent.com/52286539/78772621-549d4300-7992-11ea-95e9-88600ef057da.png)

**Comment by christianwade** [comment]
Thanks for pointing out. The fix is now in review. Trying to figure confirm deployment schedule options for AS client libs, which will be required ...

**Comment by christianwade** [comment]
This is now fixed in new release 5.0.4

**Comment by jnissley** [comment]
I upgraded to 5.0.4 and updated AS client libs, and I still get the "TOM Internal Serialization Error Occured" error with comparisons involving an open PBI desktop file or a published dataset through XMLA endpoint. It does work for comparisons between two PBITs

Note that Desktop has "Enhanced Metadata" activated (so both Desktop and the published AS instance are at 1520 compatibility level) and the dataset is in a premium capacity with XMLA Read/Write turned on.

**Comment by samaguire** [comment]
Thanks! it's working as advertised when i compare the two files again.

**Comment by christianwade** [comment]
> I upgraded to 5.0.4 and updated AS client libs, and I still get the "TOM Internal Serialization Error Occured" error with comparisons involving an open PBI desktop file or a published dataset through XMLA endpoint. It does work for comparisons between two PBITs
> 
> Note that Desktop has "Enhanced Metadata" activated (so both Desktop and the published AS instance are at 1520 compatibility level) and the dataset is in a premium capacity with XMLA Read/Write turned on.

jnissley, would it be possible to send me the PBIX so we can repro on our side?

**Comment by christianwade** [comment]
jnissley, thanks for the pbix. I have a repro. Forwarding to engineering now. I'll get back to you as soon as I have an update ...

**Comment by samaguire** [comment]
I did some further testing and like jnissley have found this is only working when comparing PBIT files. Though, instead of comparing against the XMLA endpoint I was comparing against PBI desktop instances.

My test set for this is attached. Everything is in compatability mode 1520.

- Comparing desktop instance to desktop instance didn't work.
- Comparing desktop instance to desktop file, and vice versa didn't work.
- Comparing desktop file to desktop file did work.

FYI: I was able to successfully use Tabular Editor to update the File2 instance (adding a new measure) before creating the PBIX/PBIT files.

[ALM Toolkit Test Set.zip](https://github.com/microsoft/Analysis-Services/files/4506512/ALM.Toolkit.Test.Set.zip)

**Comment by christianwade** [comment]
Thanks samaguire. Hoping it just needs the next Destkop release with latest AS engine build, but still confirming ...

**Comment by christianwade** [comment]
New TOM released and here's a new version of ALM Toolkit: https://github.com/microsoft/Analysis-Services/releases/tag/5.0.5

Seems to be working with both PBIT and PBIX this time. Please confirm. Thx.

**Comment by jnissley** [comment]
Works now, thanks!

**Comment by samaguire** [comment]
> New TOM released and here's a new version of ALM Toolkit: https://github.com/microsoft/Analysis-Services/releases/tag/5.0.5
> 
> Seems to be working with both PBIT and PBIX this time. Please confirm. Thx.

Yes, very much is working! All my previous test have worked. Thanks! 👍

**Comment by christianwade** [comment]
Great to hear!
